
version: 1.0.{build}

platform: Any CPU

build_script:

- ps: >-
    git clone  --branch=master https://github.com/AfricasTalkingLtd/africastalking.Net.git C:\projects\africastalking
    dotnet restore -v quiet
    dotnet build /p:configuration=Release /p:Version=$($env:appveyor_build_version)
    dotnet test
    .\build\build.cmd